name: gh-pages

on:
  push:
    branches:
      - master

  repository_dispatch:
    types: [update_post]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: pull contents
        run: |
          git clone https://github.com/k-wa-wa/wa_wa-cms zenn-contents

          cargo install mcm
          mcm export -s=zenn -t=hugo-robust --source_dir=../zenn-contents

          sed "s/baseURL = \"https:\/\/example.com\"/baseURL = \"https:\/\/k-wa-wa.github.io\/wa_wa-techblog\"/" config.toml > config.toml
          mv static/ temp/
          mv temp/ static/wa_wa-techblog/

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: build
        run: hugo --minify

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
