name: gh-pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: install deps
        run: go install
        working-directory: ./microcms

      - name: pull microcmsBlog & generate md files
        run: go run .
        working-directory: ./microcms
        env:
          X_MICROCMS_API_KEY: ${{ secrets.X_MICROCMS_API_KEY }}
          MICROCMS_BASE_URL: ${{ secrets.MICROCMS_BASE_URL }}
          MD_OUTPUT_DIR: ../content/ko-techblog

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: build
        run: hugo --minify

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public